// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrokeyZwLdlOqGI3d2E7mtC3Rp90yXNWU',
    appId: '1:88546278361:web:ee201530e501ca603077c8',
    messagingSenderId: '88546278361',
    projectId: 'smit-hackathon-8285e',
    authDomain: 'smit-hackathon-8285e.firebaseapp.com',
    storageBucket: 'smit-hackathon-8285e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa33YfSgdu7dx6i1yk418odqKYJCzgw9o',
    appId: '1:88546278361:android:953e31403f49d38e3077c8',
    messagingSenderId: '88546278361',
    projectId: 'smit-hackathon-8285e',
    storageBucket: 'smit-hackathon-8285e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXkL28URGOjlgcRkQMYOWw-pU5ewAERJo',
    appId: '1:88546278361:ios:dcb77c6683d114103077c8',
    messagingSenderId: '88546278361',
    projectId: 'smit-hackathon-8285e',
    storageBucket: 'smit-hackathon-8285e.firebasestorage.app',
    iosBundleId: 'com.example.hackathonSmit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXkL28URGOjlgcRkQMYOWw-pU5ewAERJo',
    appId: '1:88546278361:ios:dcb77c6683d114103077c8',
    messagingSenderId: '88546278361',
    projectId: 'smit-hackathon-8285e',
    storageBucket: 'smit-hackathon-8285e.firebasestorage.app',
    iosBundleId: 'com.example.hackathonSmit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrokeyZwLdlOqGI3d2E7mtC3Rp90yXNWU',
    appId: '1:88546278361:web:882cd04c165618ce3077c8',
    messagingSenderId: '88546278361',
    projectId: 'smit-hackathon-8285e',
    authDomain: 'smit-hackathon-8285e.firebaseapp.com',
    storageBucket: 'smit-hackathon-8285e.firebasestorage.app',
  );
}
